import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/common/Sidebar";
import Navbar from "@/components/common/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="w-[100vw] h-[100vh] overflow-hidden">
          {/* topbar */}
          <div className="w-full h-[7vh]">
            <Navbar />
          </div>
          <div className="w-full h-[93vh] flex flex-row ">
            <div className="w-[20vw] h-full">
              <Sidebar />
            </div>
            <div className="flex-1 h-full overflow-auto">{children}</div>
          </div>
        </main>
      </body>
    </html>
  );
}
